CFLAGS = -std=gnu11 -Wall -Werror -Wextra -O2

.PHONY: all clean

all: task1 task2

clean: $(RM) task1/task1_a task1/task1_b task2/task2_a task2/task2_b

task1: task1/task1_a.c task1/task1_a task1/task1_b.c task1/task1_b

task2: task2/task2_a.c task2/task2_a task2/task2_b.c task2/task2_b